# https://taskfile.dev

version: "3"

vars:
  APP_NAME: "hermans"

tasks:
  run:
    desc: "Build and run application"
    aliases:
      - r
    env:
      HMS_DATABASE_DSN: "db/orders.sqlite"
    cmds:
      - go run cmd/{{.APP_NAME}}/main.go {{.CLI_ARGS}}

  run-web:
    desc: "Run web application in dev mode"
    aliases:
      - rw
      - web
    dir: webapp
    cmds:
      - npm run dev

  integrationtests:
    desc: "Run integrationtests"
    aliases:
      - it
    cmds:
      - goat --params integrationtests/params.local.toml {{or .CLI_ARGS "integrationtests/tests"}}
